### ISSUE TITLE
To-Do list for aggregation

### ISSUE THREAD

**Issue by kidrahahjo** [glotzerlab/signac-flow#362]
### Description
Even though #335 introduces most of the changes required for aggregation, a few more pull requests are needed to get everything in place. This issue lists all the To-Do items for aggregation which are to be addressed in

### Related to #335 
- [x] Descriptive Variable Names i.e. variable names like `_aggregator_per_group`, `_stored_aggregates` doesn't seem to be immediately obvious for developers so a proper description of these variables is necessary.
- [x] Refactor tests as per this [comment](https://github.com/glotzerlab/signac-flow/pull/335#discussion_r506731035)
- [x] The private methods like `_fetch_status`, `_get_group_status`, etc are fairly complicated. We have to reduce the complexity and try to keep as minimum complexity as possible. (Refer these comments https://github.com/glotzerlab/signac-flow/pull/335#discussion_r504689525, https://github.com/glotzerlab/signac-flow/pull/335#discussion_r504698327, https://github.com/glotzerlab/signac-flow/pull/335#discussion_r504698752)
- [x] Normalize the parallelization process of operations, status fetching. Refer to this [comment](https://github.com/glotzerlab/signac-flow/pull/335#discussion_r504698752)
- [x] [Check for singleton groups](https://github.com/glotzerlab/signac-flow/pull/335/files/a4f0fe6f2769e83b882d4e7a1e5ca6f0ea342330#r492354699)
- [x] Remove all parallelization logic from status checks, inline the calls to methods like `_get_job_status` etc, and see how much redundant processing is being done that can be optimized away(https://github.com/glotzerlab/signac-flow/pull/335/files/a4f0fe6f2769e83b882d4e7a1e5ca6f0ea342330#r504698752)
- [ ] Update the API for [`run_operations`](https://github.com/glotzerlab/signac-flow/pull/335/files/a4f0fe6f2769e83b882d4e7a1e5ca6f0ea342330#r519890035)
- [x] Remove duplicated aggregate validation [here](https://github.com/glotzerlab/signac-flow/pull/335/files/a4f0fe6f2769e83b882d4e7a1e5ca6f0ea342330#r520249420).
- [ ] Add unit tests that properly tests unit operations, rather than the complex integration tests like [this one](https://github.com/glotzerlab/signac-flow/pull/335/files/a4f0fe6f2769e83b882d4e7a1e5ca6f0ea342330#r507204478)
- [x] Update the `JobsCursor` to handle aggregates ([see this comment](https://github.com/glotzerlab/signac-flow/pull/335/files/a4f0fe6f2769e83b882d4e7a1e5ca6f0ea342330#r506732149))
- [x] Replace `distinct_jobs` with a [filter](https://github.com/glotzerlab/signac-flow/pull/335/files/a4f0fe6f2769e83b882d4e7a1e5ca6f0ea342330#r474954755) in `_fetch_status`
- [x] Improve consistency of sequence types used for sequences of jobs (both those representing aggregates and those representing individual jobs), see [here](https://github.com/glotzerlab/signac-flow/pull/335/files/a4f0fe6f2769e83b882d4e7a1e5ca6f0ea342330#r521368031). **Use tuples, not lists.**

### Future Changes which needs to be done
- [x] #335 introduces most of the changes but since I had to split the PR, I didn't include the support of actual aggregation. Methods like `get_job_status`, `_select_jobs_from_args`, etc need to be refactored.
- [x] Finalize how the status output should look like
- [ ] Improve documentation as per this comment https://github.com/glotzerlab/signac-flow/pull/464#discussion_r596448131
- [ ] Address things according to this comment https://github.com/glotzerlab/signac-flow/issues/370#issuecomment-802102276

@bdice @vyasr I have mentioned the to-do items. If I missed any point, please add. Apart from this, we can finalize how should we move ahead from here and wind up this project.

**Comment by bdice** [comment]
I reviewed this list with @kidrahahjo. We looked at the unchecked boxes and we think that all the items are complete or out of scope (e.g. renaming `_JobOperation` to something else). We aren't going to check those boxes because we're not 100% sure but all of the to-do items have been addressed to the best of our knowledge.
